CREATE TABLE "promo_blocks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promo_blocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text NOT NULL,
	"product_id" integer NOT NULL,
	CONSTRAINT "promo_blocks_product_id_unique" UNIQUE("product_id")
);
--> statement-breakpoint
ALTER TABLE "promo_blocks" ADD CONSTRAINT "promo_blocks_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;