export const TEST_IDS = {
  nav: {
    signup: 'nav-signup',
    signin: 'nav-signin',
    signout: 'nav-signout',
    account: 'nav-account',
    catalog: 'nav-catalog',
  },
  auth: {
    email: 'auth-email',
    password: 'auth-password',
    submit: 'auth-submit',
    error: 'auth-error',
  },
  catalog: {
    list: 'catalog-list',
    item: 'catalog-item',
    itemName: 'catalog-item-name',
    itemPrice: 'catalog-item-price',
    itemAvailability: 'catalog-item-availability',
    empty: 'catalog-empty',
    filters: 'catalog-filters',
    pagination: 'catalog-pagination',
    pagePrev: 'catalog-page-prev',
    pageNext: 'catalog-page-next',
  },
  filter: {
    category: 'filter-category',
    priceMin: 'filter-price-min',
    priceMax: 'filter-price-max',
    available: 'filter-available',
    search: 'filter-search',
    reset: 'filter-reset',
  },
  smoke: 'main-heading',
} as const;
