export const TEST_IDS = {
  nav: {
    signup: 'nav-signup',
    signin: 'nav-signin',
    signout: 'nav-signout',
    account: 'nav-account',
    catalog: 'nav-catalog',
    cart: 'nav-cart',
  },
  auth: {
    email: 'auth-email',
    password: 'auth-password',
    submit: 'auth-submit',
    error: 'auth-error',
  },
  catalog: {
    list: 'catalog-list',
    item: 'catalog-item',
    itemName: 'catalog-item-name',
    itemPrice: 'catalog-item-price',
    itemAvailability: 'catalog-item-availability',
    empty: 'catalog-empty',
    filters: 'catalog-filters',
    pagination: 'catalog-pagination',
    pagePrev: 'catalog-page-prev',
    pageNext: 'catalog-page-next',
  },
  filter: {
    category: 'filter-category',
    priceMin: 'filter-price-min',
    priceMax: 'filter-price-max',
    available: 'filter-available',
    search: 'filter-search',
    reset: 'filter-reset',
  },
  home: {
    list: 'home-promo',
    item: 'home-promo-item',
  },
  product: {
    name: 'product-name',
    price: 'product-price',
    description: 'product-description',
    addToCart: 'product-add-to-cart',
  },
  cart: {
    item: 'cart-item',
    itemQty: 'cart-item-qty',
    itemRemove: 'cart-item-remove',
    total: 'cart-total',
    empty: 'cart-empty',
    checkout: 'cart-checkout',
  },
  checkout: {
    form: 'checkout-form',
    method: 'checkout-method',
    name: 'checkout-name',
    phone: 'checkout-phone',
    address: 'checkout-address',
    submit: 'checkout-submit',
  },
  order: {
    success: 'order-success',
    error: 'order-error',
    total: 'order-total',
    status: 'order-status',
  },
  account: {
    orders: 'account-orders',
    orderItem: 'account-order-item',
    ordersEmpty: 'account-orders-empty',
  },
  smoke: 'main-heading',
} as const;
