export const CATRGORIES_FIXTURE = [
  { id: 1, name: 'Процессоры' },
  { id: 2, name: 'Видеокарты' },
];

export const PRODUCTS_FIXTURE = [
  {
    id: 1,
    name: 'AMD Ryzen 5 7600X',
    price: 21990,
    isAccessible: true,
    categoryId: 1,
    description: '6 ядер',
    image: null,
  },
  {
    id: 2,
    name: 'AMD Ryzen 7 7800X3D',
    price: 45000,
    isAccessible: true,
    categoryId: 1,
    description: '8 ядер',
    image: null,
  },
  {
    id: 3,
    name: 'Intel Core i5-13600K',
    price: 25000,
    isAccessible: false,
    categoryId: 1,
    description: '14 ядер',
    image: null,
  },
  {
    id: 4,
    name: 'NVIDIA RTX 4070',
    price: 60000,
    isAccessible: true,
    categoryId: 2,
    description: '12GB',
    image: null,
  },
  {
    id: 5,
    name: 'NVIDIA RTX 4060',
    price: 35000,
    isAccessible: true,
    categoryId: 2,
    description: '8GB',
    image: null,
  },
  {
    id: 6,
    name: 'AMD Ryzen 9 7950X',
    price: 55000,
    isAccessible: false,
    categoryId: 1,
    description: '16 ядер',
    image: null,
  },
  {
    id: 7,
    name: 'Intel Core i9-14900K',
    price: 65000,
    isAccessible: true,
    categoryId: 1,
    description: '24 ядра',
    image: null,
  },
  {
    id: 8,
    name: 'NVIDIA RTX 3060',
    price: 28000,
    isAccessible: true,
    categoryId: 2,
    description: '12GB',
    image: null,
  },
];
