openapi: 3.1.0
info:
  title: Computer shop app
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Money:
      type: integer
      format: int32
      minimum: 0
      description: Денежная сумма в целых рублях без копеек
